name = "chat-bubble"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
OPENAI_MODEL = "gpt-4o"
SYSTEM_PROMPT = "You are a helpful assistant."
FRONTEND_CENTERED = "false"
FRONTEND_DEBUG_MODE = "false"
THEME_COLOR = "#43C76A"
THEME_ACCENT_COLOR = "#F72C25"
SHOW_HEADER = "true"
EXPLANATION_TEXT = "Master any concept through explanation. Break down complex ideas into simple terms, identify knowledge gaps as you teach, and build genuine understanding by articulating what you've learned in your own words."
